In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("tips.csv")

In [4]:
df[(df['day']=='Sat') & (df['time']=='Dinner')]

     total_bill   tip     sex smoker  day    time  size
19        20.65  3.35    Male     No  Sat  Dinner     3
20        17.92  4.08    Male     No  Sat  Dinner     2
21        20.29  2.75  Female     No  Sat  Dinner     2
22        15.77  2.23  Female     No  Sat  Dinner     2
23        39.42  7.58    Male     No  Sat  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
238       35.83  4.67  Female     No  Sat  Dinner     3
239       29.03  5.92    Male     No  Sat  Dinner     3
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2
242       17.82  1.75    Male     No  Sat  Dinner     2

[87 rows x 7 columns]